import { Trip, Shipment, ChatMessage, IncomingRequest, TrackingStep } from './types';
import { colors } from './theme';

export const mockUser = {
  uid: 'user_001',
  displayName: 'Waleed Alkhateeb',
  phone: '+971 50 123 4567',
  email: 'waleed@email.com',
  avatarColor: colors.teal,
  verificationStatus: 'verified' as const,
  trustScore: 82,
  totalDeliveries: 7,
  rating: 4.9,
  roles: ['sender', 'courier'] as const,
};

export const mockTravelers: Trip[] = [
  {
    tripId: 'trip_001',
    courierId: 'user_002',
    courierName: 'Sarah Khaled',
    courierAvatar: colors.orange,
    courierRating: 4.9,
    courierReviews: 23,
    originCity: 'Dubai',
    originCountry: 'UAE',
    destinationCity: 'Cairo',
    destinationCountry: 'Egypt',
    travelDate: 'Apr 14',
    flight: 'Emirates EK925',
    totalCapacityKg: 5,
    remainingCapacityKg: 3,
    pricePerKg: 4,
    acceptedCategories: ['gift', 'documents', 'clothing', 'electronics'],
    pickupZone: 'Dubai Marina',
    deliveryZone: 'Nasr City',
    status: 'active',
  },
  {
    tripId: 'trip_002',
    courierId: 'user_003',
    courierName: 'Omar Taha',
    courierAvatar: colors.tealLight,
    courierRating: 4.7,
    courierReviews: 15,
    originCity: 'Dubai',
    originCountry: 'UAE',
    destinationCity: 'Cairo',
    destinationCountry: 'Egypt',
    travelDate: 'Apr 15',
    flight: 'FlyDubai FZ1733',
    totalCapacityKg: 7,
    remainingCapacityKg: 5,
    pricePerKg: 3,
    acceptedCategories: ['gift', 'documents', 'clothing'],
    pickupZone: 'JLT',
    deliveryZone: 'Heliopolis',
    status: 'active',
  },
  {
    tripId: 'trip_003',
    courierId: 'user_004',
    courierName: 'Fatima Rizk',
    courierAvatar: colors.nightLight,
    courierRating: 5.0,
    courierReviews: 31,
    originCity: 'Dubai',
    originCountry: 'UAE',
    destinationCity: 'Cairo',
    destinationCountry: 'Egypt',
    travelDate: 'Apr 16',
    flight: 'EgyptAir MS913',
    totalCapacityKg: 3,
    remainingCapacityKg: 2,
    pricePerKg: 5,
    acceptedCategories: ['gift', 'documents', 'clothing', 'electronics', 'food'],
    pickupZone: 'Downtown Dubai',
    deliveryZone: 'Maadi',
    status: 'active',
  },
];

export const mockShipments: Shipment[] = [
  {
    shipmentId: 'ship_001',
    senderId: 'user_001',
    courierId: 'user_002',
    courierName: 'Sarah Khaled',
    tripId: 'trip_001',
    destinationCity: 'Cairo',
    destinationCountry: 'Egypt',
    category: 'gift',
    description: 'Birthday gift - perfume set',
    weightKg: 1.5,
    declaredValue: 40,
    receiverName: 'Ahmed Mohamed',
    receiverPhone: '+20 112 345 6789',
    receiverAddress: 'Nasr City, Cairo',
    status: 'in_transit',
    agreedPrice: 12,
    platformFee: 1.44,
    deliveryPin: '847293',
  },
  {
    shipmentId: 'ship_002',
    senderId: 'user_001',
    courierId: 'user_005',
    courierName: 'Ahmed N.',
    tripId: 'trip_005',
    destinationCity: 'Khartoum',
    destinationCountry: 'Sudan',
    category: 'documents',
    description: 'University documents',
    weightKg: 0.3,
    declaredValue: 0,
    receiverName: 'Mohamed Ali',
    receiverPhone: '+249 91 234 5678',
    receiverAddress: 'Khartoum Central',
    status: 'delivered',
    agreedPrice: 8,
    platformFee: 0.96,
    deliveryPin: '392041',
  },
];

export const mockIncomingRequests: IncomingRequest[] = [
  {
    id: 'req_001',
    senderName: 'Youssef Ali',
    senderAvatar: colors.nightLight,
    senderRating: 4.6,
    senderReviews: 9,
    category: 'electronics',
    weightKg: 2,
    price: 18,
    description: 'Laptop charger and phone case',
    hasPhoto: true,
  },
  {
    id: 'req_002',
    senderName: 'Mona Hassan',
    senderAvatar: colors.orange,
    senderRating: 4.8,
    senderReviews: 14,
    category: 'gift',
    weightKg: 1,
    price: 10,
    description: 'Perfume set - birthday gift, sealed box',
    hasPhoto: true,
  },
];

export const mockTrackingSteps: TrackingStep[] = [
  { label: 'Package Handed Over', time: 'Apr 14, 10:30 AM', location: 'Dubai Marina Mall', done: true },
  { label: 'Traveler Departed', time: 'Apr 14, 3:45 PM', location: 'DXB Terminal 3', done: true },
  { label: 'In Transit', time: 'ETA: 5:30 PM Cairo', location: '', done: false, current: true },
  { label: 'Traveler Arrived', time: 'Pending', location: '', done: false },
  { label: 'Delivered to Receiver', time: 'Pending', location: '', done: false },
];

export const mockChatMessages: ChatMessage[] = [
  { id: '1', senderId: 'user_001', text: "Hi Sarah! The package is a birthday gift, wrapped in a small box.", timestamp: '10:12 AM' },
  { id: '2', senderId: 'user_002', text: "Got it! I can pick it up from Dubai Marina area. Does 10:30 AM work?", timestamp: '10:14 AM' },
  { id: '3', senderId: 'user_001', text: "Perfect. I'll be at the mall entrance.", timestamp: '10:15 AM' },
  { id: '4', senderId: 'user_002', text: "Great, see you there! I'll inspect and photograph the package at pickup.", timestamp: '10:16 AM' },
];

export const COURIER_MILESTONES = [
  { label: 'Picked Up', icon: '📦', description: 'Package in your possession' },
  { label: 'Departed', icon: '✈️', description: "You've boarded / left origin city" },
  { label: 'Arrived', icon: '🛬', description: "You've landed at destination" },
  { label: 'Out for Delivery', icon: '🚗', description: 'On the way to meet receiver' },
];
